version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=kedar
    



  user_app:
    build: 
      context: ./
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:kedar@postgres:5432/postgres
    
    ports:
      - "3000:3000"
    
    depends_on:
      - postgres